const POA = 'poa'
const DAI = 'dai'
const POA_SOKOL = 'sokol'
const MAINNET = 'mainnet'
const ROPSTEN = 'ropsten'
const RINKEBY = 'rinkeby'
const KOVAN = 'kovan'
const GOERLI_TESTNET = 'goerli_testnet'
const CLASSIC = 'classic'
const RSK = 'rsk'
const RSK_TESTNET = 'rsk_testnet'
const LOCALHOST = 'localhost'
const CELO = 'celo'
const CELO_ALFAJORES_TESTNET = 'celo-alfajores'
const CELO_BAKLAVA_TESTNET = 'celo-baklava'

const ETH_TICK = 'ETH'
const POA_TICK = 'POA'
const RSK_TICK = 'RBTC'
const CLASSIC_TICK = 'ETC'
const CELO_TICK = 'CELO'

const MAINNET_CHAIN_ID = '0x01'
const ROPSTEN_CHAIN_ID = '0x03'
const RINKEBY_CHAIN_ID = '0x04'
const KOVAN_CHAIN_ID = '0x2a'
const GOERLI_TESTNET_CHAIN_ID = '0x5'
const POA_CHAIN_ID = '0x63'
const DAI_CHAIN_ID = '0x64'
const POA_SOKOL_CHAIN_ID = '0x4D'
const RSK_CHAIN_ID = '0x1E'
const RSK_TESTNET_CHAIN_ID = '0x1F'
const CLASSIC_CHAIN_ID = '0x3D'
const CELO_CHAIN_ID = '0xA4EC'
const CELO_ALFAJORES_TESTNET_CHAIN_ID = '0xAEF3'
const CELO_BAKLAVA_TESTNET_CHAIN_ID = '0xF370'

const POA_CODE = 99
const DAI_CODE = 100
const POA_SOKOL_CODE = 77
const MAINNET_CODE = 1
const ROPSTEN_CODE = 3
const RINKEBY_CODE = 4
const KOVAN_CODE = 42
const GOERLI_TESTNET_CODE = 5
const CLASSIC_CODE = 61
const RSK_CODE = 30
const RSK_TESTNET_CODE = 31
const CELO_CODE = 42220
const CELO_ALFAJORES_TESTNET_CODE = 44787
const CELO_BAKLAVA_TESTNET_CODE = 62320


const MAINNET_NETWORK_ID = '1'
const ROPSTEN_NETWORK_ID = '3'
const RINKEBY_NETWORK_ID = '4'
const GOERLI_NETWORK_ID = '5'
const KOVAN_NETWORK_ID = '42'
const POA_NETWORK_ID = '99'
const DAI_NETWORK_ID = '100'
const POA_SOKOL_NETWORK_ID = '77'
const CLASSIC_NETWORK_ID = '61'
const RSK_NETWORK_ID = '30'
const RSK_TESTNET_NETWORK_ID = '31'
const CELO_NETWORK_ID = '42220'
const CELO_ALFAJORES_NETWORK_ID = '44787'
const CELO_BAKLAVA_NETWORK_ID = '62320'

const NETWORK_TYPE_TO_ID_MAP = {
  [ROPSTEN]: { networkId: ROPSTEN_NETWORK_ID, chainId: ROPSTEN_CHAIN_ID },
  [RINKEBY]: { networkId: RINKEBY_NETWORK_ID, chainId: RINKEBY_CHAIN_ID },
  [KOVAN]: { networkId: KOVAN_NETWORK_ID, chainId: KOVAN_CHAIN_ID },
  [GOERLI_TESTNET]: { networkId: GOERLI_NETWORK_ID, chainId: GOERLI_TESTNET_CHAIN_ID },
  [MAINNET]: { networkId: MAINNET_NETWORK_ID, chainId: MAINNET_CHAIN_ID },
  [POA]: { networkId: POA_NETWORK_ID, chainId: POA_CHAIN_ID },
  [DAI]: { networkId: DAI_NETWORK_ID, chainId: DAI_CHAIN_ID },
  [POA_SOKOL]: { networkId: POA_SOKOL_NETWORK_ID, chainId: POA_SOKOL_CHAIN_ID },
  [CLASSIC]: { networkId: CLASSIC_NETWORK_ID, chainId: CLASSIC_CHAIN_ID },
  [RSK]: { networkId: RSK_NETWORK_ID, chainId: RSK_CHAIN_ID },
  [RSK_TESTNET]: { networkId: RSK_TESTNET_NETWORK_ID, chainId: RSK_TESTNET_CHAIN_ID },
  [CELO]: { networkId: CELO_NETWORK_ID, chainId: CELO_CHAIN_ID},
  [CELO_ALFAJORES_TESTNET]: { networkId: CELO_ALFAJORES_NETWORK_ID, chainId: CELO_ALFAJORES_TESTNET_CHAIN_ID},
  [CELO_BAKLAVA_TESTNET]: { networkId: CELO_BAKLAVA_NETWORK_ID, chainId: CELO_BAKLAVA_TESTNET_CHAIN_ID},
}

const POA_DISPLAY_NAME = 'POA'
const DAI_DISPLAY_NAME = 'xDai'
const POA_SOKOL_DISPLAY_NAME = 'Sokol Testnet'
const MAINNET_DISPLAY_NAME = 'Ethereum'
const ROPSTEN_DISPLAY_NAME = 'Ropsten Testnet'
const RINKEBY_DISPLAY_NAME = 'Rinkeby Testnet'
const KOVAN_DISPLAY_NAME = 'Kovan Testnet'
const GOERLI_TESTNET_DISPLAY_NAME = 'Görli Testnet'
const CLASSIC_DISPLAY_NAME = 'Ethereum Classic'
const RSK_DISPLAY_NAME = 'RSK'
const RSK_TESTNET_DISPLAY_NAME = 'RSK Testnet'
const CELO_DISPLAY_NAME = 'CELO'
const CELO_ALFAJORES_TESTNET_DISPLAY_NAME = 'CELO Alfajores'
const CELO_BAKLAVA_TESTNET_DISPLAY_NAME = 'CELO Baklava'

const DROPDOWN_POA_DISPLAY_NAME = POA_DISPLAY_NAME
const DROPDOWN_DAI_DISPLAY_NAME = DAI_DISPLAY_NAME
const DROPDOWN_POA_SOKOL_DISPLAY_NAME = POA_SOKOL_DISPLAY_NAME
const DROPDOWN_MAINNET_DISPLAY_NAME = MAINNET_DISPLAY_NAME
const DROPDOWN_ROPSTEN_DISPLAY_NAME = ROPSTEN_DISPLAY_NAME
const DROPDOWN_RINKEBY_DISPLAY_NAME = RINKEBY_DISPLAY_NAME
const DROPDOWN_KOVAN_DISPLAY_NAME = KOVAN_DISPLAY_NAME
const DROPDOWN_GOERLI_TESTNET_DISPLAY_NAME = GOERLI_TESTNET_DISPLAY_NAME
const DROPDOWN_CLASSIC_DISPLAY_NAME = CLASSIC_DISPLAY_NAME
const DROPDOWN_RSK_DISPLAY_NAME = RSK_DISPLAY_NAME
const DROPDOWN_RSK_TESTNET_DISPLAY_NAME = RSK_TESTNET_DISPLAY_NAME
const DROPDOWN_CELO_DISPLAY_NAME = CELO_DISPLAY_NAME
const DROPDOWN_CELO_ALFAJORES_TESTNET_DISPLAY_NAME = CELO_ALFAJORES_TESTNET_DISPLAY_NAME
const DROPDOWN_CELO_BAKLAVA_TESTNET_DISPLAY_NAME = CELO_BAKLAVA_TESTNET_DISPLAY_NAME

const chainTypes = {
  TEST: 1,
  PROD: 2,
}

const hdRSKMainnetPath = `m/44'/137'/0'/0`
const hdRSKTestnetPath = `m/44'/37310'/0'/0`
const hdETCPath = `m/44'/61'/0'/0`
const hdCELOPath = `m/44'/52752'/0'`

const customDPaths = {}
customDPaths[RSK] = hdRSKMainnetPath
customDPaths[RSK_TESTNET] = hdRSKTestnetPath
customDPaths[CLASSIC] = hdETCPath
customDPaths[CELO] = hdCELOPath
customDPaths[CELO_ALFAJORES_TESTNET] = hdCELOPath
customDPaths[CELO_BAKLAVA_TESTNET] = hdCELOPath

module.exports = {
  POA,
  POA_TICK,
  ETH_TICK,
  RSK_TICK,
  CLASSIC_TICK,
  CELO_TICK,
  MAINNET_CHAIN_ID,
  ROPSTEN_CHAIN_ID,
  RINKEBY_CHAIN_ID,
  KOVAN_CHAIN_ID,
  GOERLI_TESTNET_CHAIN_ID,
  POA_CHAIN_ID,
  DAI_CHAIN_ID,
  POA_SOKOL_CHAIN_ID,
  RSK_CHAIN_ID,
  RSK_TESTNET_CHAIN_ID,
  CLASSIC_CHAIN_ID,
  CELO_CHAIN_ID,
  CELO_ALFAJORES_TESTNET_CHAIN_ID,
  CELO_BAKLAVA_TESTNET_CHAIN_ID,
  DAI,
  POA_SOKOL,
  MAINNET,
  ROPSTEN,
  RINKEBY,
  KOVAN,
  GOERLI_TESTNET,
  CLASSIC,
  RSK,
  RSK_TESTNET,
  CELO,
  CELO_ALFAJORES_TESTNET,
  CELO_BAKLAVA_TESTNET,
  LOCALHOST,
  POA_CODE,
  DAI_CODE,
  POA_SOKOL_CODE,
  MAINNET_CODE,
  ROPSTEN_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  GOERLI_TESTNET_CODE,
  CLASSIC_CODE,
  CELO_CODE,
  CELO_ALFAJORES_TESTNET_CODE,
  CELO_BAKLAVA_TESTNET_CODE,
  RSK_CODE,
  RSK_TESTNET_CODE,
  POA_DISPLAY_NAME,
  DAI_DISPLAY_NAME,
  POA_SOKOL_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  GOERLI_TESTNET_DISPLAY_NAME,
  CLASSIC_DISPLAY_NAME,
  RSK_DISPLAY_NAME,
  RSK_TESTNET_DISPLAY_NAME,
  CELO_DISPLAY_NAME,
  CELO_ALFAJORES_TESTNET_DISPLAY_NAME,
  CELO_BAKLAVA_TESTNET_DISPLAY_NAME,
  DROPDOWN_POA_DISPLAY_NAME,
  DROPDOWN_DAI_DISPLAY_NAME,
  DROPDOWN_POA_SOKOL_DISPLAY_NAME,
  DROPDOWN_MAINNET_DISPLAY_NAME,
  DROPDOWN_ROPSTEN_DISPLAY_NAME,
  DROPDOWN_RINKEBY_DISPLAY_NAME,
  DROPDOWN_KOVAN_DISPLAY_NAME,
  DROPDOWN_GOERLI_TESTNET_DISPLAY_NAME,
  DROPDOWN_CLASSIC_DISPLAY_NAME,
  DROPDOWN_RSK_DISPLAY_NAME,
  DROPDOWN_RSK_TESTNET_DISPLAY_NAME,
  DROPDOWN_CELO_DISPLAY_NAME,
  DROPDOWN_CELO_ALFAJORES_TESTNET_DISPLAY_NAME,
  DROPDOWN_CELO_BAKLAVA_TESTNET_DISPLAY_NAME,
  chainTypes,
  customDPaths,
  NETWORK_TYPE_TO_ID_MAP,
}
